In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns = ['id' , 'Unnamed: 32'] , inplace = True)

In [6]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

TRAIN TEST SPLIT

In [7]:
X_train , X_test , y_train , y_test  = train_test_split(df.iloc[:,1:] , df.iloc[:,0] , test_size = 0.2)

SCALING

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
X_train

array([[-0.83145115,  3.37619798, -0.87809755, ..., -1.30892808,
         0.01731102, -0.60627752],
       [-0.43022065,  0.35085838, -0.40931982, ..., -0.07948615,
        -1.07025419,  0.03011831],
       [ 0.21573198,  0.7611918 ,  0.41392979, ...,  2.01337597,
        -0.05413487,  1.68399177],
       ...,
       [-0.92251055, -1.45739057, -0.9647554 , ..., -1.16364984,
        -0.25735874, -0.40224221],
       [ 0.17589349, -1.04473889,  0.11557918, ...,  0.14354879,
         0.33167293, -0.13127469],
       [-0.79730387,  0.46677178, -0.80835861, ..., -0.50294702,
        -0.11287927,  0.21688078]])

In [10]:
X_test

array([[ 1.61292469,  0.67309762,  1.56524127, ...,  1.88047158,
        -0.20972814, -0.44002653],
       [-0.36761732,  0.49227272, -0.38951231, ..., -0.91189533,
        -0.65428034, -0.15070663],
       [-0.15135123,  1.32916743, -0.16585252, ...,  0.04119714,
        -0.39548746, -0.55769768],
       ...,
       [-0.11435835, -0.30984797, -0.16296393, ..., -0.84804012,
        -0.87338107, -0.76443186],
       [-0.74039175, -1.97668258, -0.75677655, ..., -1.04724393,
         0.77781282, -0.53772597],
       [-0.60949385,  2.08260449, -0.63132899, ..., -0.68045839,
        -0.71937549, -0.12749626]])

LABELENCODER

In [11]:
label = LabelEncoder()
y_train = label.fit_transform(y_train)
y_test = label.transform(y_test)

In [12]:
y_train

array([0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,

In [26]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [17]:
X_train_tensor.shape

torch.Size([455, 30])

CREATING THE NEURAL MODEL AND TRAINING IT

In [34]:
# DEFINING THE MODEL
class nnclass():
  def __init__(self, x):
    self.weights = torch.rand(x.shape[1] , 1 , dtype = torch.float64 , requires_grad = True)
    self.bias = torch.zeros(1 , dtype = torch.float64 , requires_grad = True)

  def forward(self , x):
    z = torch.matmul(x , self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self , y_pred , y):
    # clamp prediction to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred , epsilon , 1 - epsilon)

    # calculation loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1- y_train_tensor) * torch.log(1-y_pred)).mean()
    return loss

In [35]:
# defining parameters
learning_rate = 00.1
epochs = 25

In [20]:
model = nnclass(X_train_tensor)
model.weights

tensor([[0.4759],
        [0.7803],
        [0.1882],
        [0.3349],
        [0.0164],
        [0.2728],
        [0.0971],
        [0.0195],
        [0.6398],
        [0.4983],
        [0.3101],
        [0.6141],
        [0.0806],
        [0.9983],
        [0.7571],
        [0.4287],
        [0.2555],
        [0.0352],
        [0.9187],
        [0.5418],
        [0.3796],
        [0.4864],
        [0.5904],
        [0.8264],
        [0.6432],
        [0.3944],
        [0.4657],
        [0.4124],
        [0.2222],
        [0.1625]], dtype=torch.float64, requires_grad=True)

In [21]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

TRAINING PIPELINE

In [36]:
# creating the model
model = nnclass(X_train_tensor)

# this entire process is done in loop as per the epoches defined
for epoch in range(epochs):
  # forward [ass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred , y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients - to reset the gradient matrix after each epoch
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print
  print(f'Epoch:{epoch+1} , Loss: {loss.item()}')

Epoch:1 , Loss: 3.8299431785303053
Epoch:2 , Loss: 3.7214315179729125
Epoch:3 , Loss: 3.6097758156898596
Epoch:4 , Loss: 3.4938044532578796
Epoch:5 , Loss: 3.375774283374538
Epoch:6 , Loss: 3.2498945891185627
Epoch:7 , Loss: 3.120155300878726
Epoch:8 , Loss: 2.987354743117012
Epoch:9 , Loss: 2.8522489677837126
Epoch:10 , Loss: 2.715069188781085
Epoch:11 , Loss: 2.5756024304532232
Epoch:12 , Loss: 2.43811660661643
Epoch:13 , Loss: 2.2980999659423653
Epoch:14 , Loss: 2.152650216719164
Epoch:15 , Loss: 2.0109070532598765
Epoch:16 , Loss: 1.8753415259816977
Epoch:17 , Loss: 1.744548133559331
Epoch:18 , Loss: 1.620325868566315
Epoch:19 , Loss: 1.5016843190197533
Epoch:20 , Loss: 1.3886274872726747
Epoch:21 , Loss: 1.2811337640418745
Epoch:22 , Loss: 1.1869877159677154
Epoch:23 , Loss: 1.1063378668119566
Epoch:24 , Loss: 1.0386957265212178
Epoch:25 , Loss: 0.9829484903035869


In [37]:
model.weights

tensor([[ 0.2491],
        [-0.0833],
        [-0.1829],
        [ 0.3822],
        [-0.0135],
        [ 0.2671],
        [ 0.1226],
        [-0.0191],
        [ 0.0358],
        [ 0.3909],
        [-0.1569],
        [ 0.0168],
        [ 0.1874],
        [ 0.4759],
        [ 0.1562],
        [ 0.1232],
        [ 0.2957],
        [ 0.0195],
        [ 0.7389],
        [ 0.0977],
        [-0.0708],
        [-0.1904],
        [-0.4066],
        [ 0.0438],
        [ 0.4046],
        [ 0.2971],
        [-0.2007],
        [-0.2728],
        [-0.1907],
        [-0.2121]], dtype=torch.float64, requires_grad=True)

In [38]:
model.bias

tensor([-0.0821], dtype=torch.float64, requires_grad=True)

EVALUATION

In [39]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)

print(y_pred)

tensor([[0.2438],
        [0.5506],
        [0.1424],
        [0.8146],
        [0.5409],
        [0.4090],
        [0.6983],
        [0.4041],
        [0.7324],
        [0.2667],
        [0.9900],
        [0.0636],
        [0.7542],
        [0.7006],
        [0.2652],
        [0.9413],
        [0.4178],
        [0.7758],
        [0.1791],
        [0.4524],
        [0.2681],
        [0.3024],
        [0.4670],
        [0.9099],
        [0.5437],
        [0.1291],
        [0.6233],
        [0.3548],
        [0.7484],
        [0.7610],
        [0.4656],
        [0.1264],
        [0.6076],
        [0.1730],
        [0.9899],
        [0.4702],
        [0.5736],
        [0.9083],
        [0.1440],
        [0.7432],
        [0.5352],
        [0.2249],
        [0.9198],
        [0.1432],
        [0.6464],
        [0.5605],
        [0.0857],
        [0.5322],
        [0.4517],
        [0.7690],
        [0.5723],
        [0.6231],
        [0.5472],
        [0.7218],
        [0.4011],
        [0

 the problem is that the original labels are either 0 or 1 , so we will have ot convert it to zero and 1 ( y_pred )

In [40]:
y_pred = (y_pred > 0.5).float()

print(y_pred)

tensor([[0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
      

In [41]:
accuracy = ( y_pred == y_test_tensor).float().mean()
print(f'Accuraccy: {accuracy.item()}')

Accuraccy: 0.5230840444564819


In [ ]:
# COMBINED CODE
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')
