In [5]:
import torch
import torch.nn as nn

# we need to inherit from the nn module - it contains all the functionalities for creating an nn model
class model(nn.Module):

  def __init__(self , num_features):
    #classing the constructor of the parent module- invoking the constructor of the nn class

    super().__init__()
    self.linear = nn.Linear(num_features , 1) # this shows (features in the inpt ,features in the output) - 1 feature in the output
    self.sigmoid = nn.Sigmoid()

  def forward(self , features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [6]:
# create dataset
features = torch.rand(10,5)

# create model
model = model(features.shape[1])

# call model for foward pass
model(features) # this should be the standard way of calling the function
# not this model.forward(features) - this will also work but pytoch dosent approve of this

tensor([[0.4294],
        [0.5562],
        [0.4294],
        [0.4039],
        [0.4780],
        [0.4060],
        [0.3944],
        [0.4790],
        [0.4143],
        [0.4902]], grad_fn=<SigmoidBackward0>)

In [7]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.4181,  0.4276, -0.3370, -0.3146, -0.1802]], requires_grad=True)

In [8]:
model.linear.bias

Parameter containing:
tensor([-0.1980], requires_grad=True)

In [9]:
# to visualise this entire network
!pip install torchinfo

In [10]:
from torchinfo import summary
summary(model , input_size = (10 , 5))

Layer (type:depth-idx)                   Output Shape              Param #
model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

CREATING THE NEURAL NETWORK WITH HIDDEN LAYERS

In [11]:
import torch
import torch.nn as nn

# we need to inherit from the nn module - it contains all the functionalities for creating an nn model
class model(nn.Module):

  def __init__(self , num_features):
    #classing the constructor of the parent module- invoking the constructor of the nn class

    super().__init__()
    self.linear = nn.Linear(num_features , 3) # this shows (features in the inpt ,features in the output) - 1 feature in the output
    # here the features in the output are the features in the input of the hideen layer

    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1) # input features = 2 , output features = 1
    # this is applied at the hidden layer to get the output

    self.sigmoid = nn.Sigmoid()


  def forward(self , features):
    out = self.linear(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

In [12]:
# create dataset
features = torch.rand(10,5)

# create model
model = model(features.shape[1])

# call model for foward pass
model(features) # this should be the standard way of calling the function
# not this model.forward(features) - this will also work but pytoch dosent approve of this

tensor([[0.5830],
        [0.5830],
        [0.5830],
        [0.5971],
        [0.6052],
        [0.5830],
        [0.6325],
        [0.6284],
        [0.6158],
        [0.6039]], grad_fn=<SigmoidBackward0>)

here Linear is Layer1
and Linear2 is Layer2

In [13]:
model.linear.weight

Parameter containing:
tensor([[-0.4297, -0.2711,  0.2518,  0.2092,  0.2038],
        [ 0.3642, -0.0899,  0.4229, -0.0902, -0.3295],
        [-0.3675,  0.3821,  0.4289, -0.1871,  0.3860]], requires_grad=True)

In [14]:
model.linear2.weight

Parameter containing:
tensor([[0.3202, 0.0449, 0.5204]], requires_grad=True)

In [15]:
model.linear.bias

Parameter containing:
tensor([-0.1626, -0.3638, -0.3052], requires_grad=True)

In [16]:
from torchinfo import summary
summary(model , input_size = (10 , 5))

Layer (type:depth-idx)                   Output Shape              Param #
model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [20]:
# do we always have to define the containers - we can replace the entire process of definning the forward function by definning the container
import torch
import torch.nn as nn

# we need to inherit from the nn module - it contains all the functionalities for creating an nn model
class model(nn.Module):

  def __init__(self , num_features):
    #classing the constructor of the parent module- invoking the constructor of the nn class

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features , 1),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )


  def forward(self , features):
    out = self.network(features)
    return out