In [2]:
import torch
print(torch.__version__)

2.9.0+cu126


In [3]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"using GPU: { torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available")


GPU is available
using GPU: Tesla T4


CREATING TENSOR

In [6]:
# using empty
# in the bracket u need to define the shape
a = torch.empty(2,3)

#the empty function is resposnsible for assignign a space /allocating memory and showases the values which are already present in that memory

In [7]:
# check type
type(a)

torch.Tensor

In [8]:
#using cxeros
# with the help of this function u can crate a tensor , which has all of its values initialised with zero
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
# using ones
# similar to zeros , torch also has a function to initalised the tensor with one
torch.ones(2,3)


tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
# using rand
# with the help of this function u can create a tansor which contains any value b/w 0 and 1
# assign random values with 0 and 1
torch.rand(2,3)

tensor([[0.7905, 0.6021, 0.3857],
        [0.3439, 0.7864, 0.9390]])

In [12]:
torch.rand(2,3)
#values are different from the above code

tensor([[0.2004, 0.4217, 0.4831],
        [0.6878, 0.0059, 0.1126]])

In [13]:
# use of seed
# one problem that often arrives iwth the rand fucntion is that , each time u run the function rand , it assignes new values , meaning the value wont remain the same if u run the function for the 2nd time
# this function is used in order to overcome that issue
torch.manual_seed(100)
torch.rand(2,3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
# if i run the same code again  , with the troch.manual_seed(100 , the values will remain the same
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [15]:
# using tensor
# with the help of this u can design custom tansors
torch.tensor([[1,2,3] ,[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
# more methods of creating tensors

#arange
print("using arange ->" , torch.arange(0,10))
print("using arange->", torch.arange(0,10,2))
# print tenor by defining the range
print("\n")

#using linspace
print("using linspace ->" , torch.linspace(0,10,10))
# linearly spaced , evenly spaced values
print("\n")

#using eye
print("using eye->" , torch.eye(5))
print("\n")
# identity matrix with daigonal value of 5

#using full
print("using full->", torch.full((3,3),5))
#defines the sixe of the matrix /tensor and the value with which all the cells should be initialised

using arange -> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using arange-> tensor([0, 2, 4, 6, 8])


using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


using eye-> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


using full-> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


SHAPE OF THE TENSOR

In [19]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
x.shape

torch.Size([2, 3])

In [22]:
#make a tesnor of the same shape as the laready existing tensor
y = torch.empty_like(x)
y

tensor([[137653487625776,        11662568, 137653486125584],
        [137653486125632,        11680416,        11664528]])

In [23]:
# again used for creating a tensor of the same shape as an already existign tensor but initialised with the value zeros
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [24]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [34]:
torch.rand_like(x , dtype = torch.float32)
# why would it not work ?
# our existing tesnor whoes size we want to copy has integer values which the random function assigns float values b/w 0 and 1

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [28]:
# find the type of the values in the existing tensor
x.dtype

torch.int64

In [29]:
torch.tensor([1.0,2.0,3.0] , dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [30]:
torch.tensor([1.2,3.4,5.7] , dtype = torch.int32)

tensor([1, 3, 5], dtype=torch.int32)

In [32]:
torch.tensor([1,2,3] , dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [33]:
# we can also change the data type of an already existing tensor
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

MATH OPERATIONS

In [35]:
# ADDITION
a = x+2
print(a)
print("\n")

# subtarction
b = x-2
print(b)
print("\n")

# MULTIPLICATION
c = x*2
print(c)
print("\n")

#divison
d = x/3
print(d)
print("\n")

#int division
e = (x*100)//2
print(e)
print("\n")

#mod
f = (x*100)%3
print(f)
print("\n")

#power
g = x**2
print(g)
print("\n")

tensor([[3, 4, 5],
        [6, 7, 8]])


tensor([[-1,  0,  1],
        [ 2,  3,  4]])


tensor([[ 2,  4,  6],
        [ 8, 10, 12]])


tensor([[0.3333, 0.6667, 1.0000],
        [1.3333, 1.6667, 2.0000]])


tensor([[ 50, 100, 150],
        [200, 250, 300]])


tensor([[1, 2, 0],
        [1, 2, 0]])


tensor([[ 1,  4,  9],
        [16, 25, 36]])




In [36]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])
tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])


In [37]:
# add
print(a+b)
print("\n")

# sub
print(a-b)
print("\n")

# multiply
print(a*b)
print("\n")

# div
print(a/b)
print("\n")

# power
print(a**b)
print("\n")

# mod
print(a % b)
print("\n")


tensor([[0.9357, 1.0899, 0.5967],
        [1.7253, 1.5526, 1.7335]])


tensor([[ 0.4879,  0.4852,  0.2399],
        [ 0.0776,  0.4411, -0.2205]])


tensor([[0.1594, 0.2381, 0.0746],
        [0.7426, 0.5540, 0.7391]])


tensor([[3.1790, 2.6049, 2.3445],
        [1.0942, 1.7938, 0.7743]])


tensor([[0.9267, 0.9303, 0.8560],
        [0.9180, 0.9983, 0.7614]])


tensor([[0.0401, 0.1829, 0.0615],
        [0.0776, 0.4411, 0.7565]])




In [38]:
c = torch.tensor([-1,-2,4,5-6])

In [39]:
# abs
torch.abs(c)

tensor([1, 2, 4, 1])

In [40]:
# negative
torch.neg(c)

tensor([ 1,  2, -4,  1])

In [42]:
d = torch.tensor([1.2,2.3 , 4.5])

In [43]:
# round
torch.round(d)

tensor([1., 2., 4.])

In [45]:
#ceil
torch.ceil(d)
# rounds off to the higher integer

tensor([2., 3., 5.])

In [47]:
# floor
torch.floor(d)

tensor([1., 2., 4.])

In [48]:
# clamp
# which tthe help of clamp , we can manipulate our numbers to be winten the defined range
torch.clamp(d , min=2 , max = 3)

tensor([2.0000, 2.3000, 3.0000])

REDUCTION OPERATION

In [52]:
e = torch.randint(size = (2,3) , low = 0,high = 10)
# with the help of this function we can assign random integer values
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [51]:
# sum
# with the help of this function u can get the sum of all the numbers in the given tensor
torch.sum(e)

tensor(28)

In [53]:
# sum along columns - find the sum of each column
torch.sum(e , dim = 0)

tensor([ 3, 14, 11])

In [54]:
# sum along the rows
torch.sum(e , dim = 1)

tensor([16, 12])

In [55]:
# mean
d = torch.randint(size = ( 2,3) , low = 0 , high = 10 , dtype=torch.float32)

In [57]:
torch.mean(d)
# this function only works when the values are flaot

tensor(7.3333)

In [58]:
# mean along the columns
torch.mean( d , dim = 0)

tensor([6., 7., 9.])

In [59]:
# mean along the rows
torch.mean(d , dim =1)

tensor([7.6667, 7.0000])

In [61]:
# median
torch.median(d)

tensor(7.)

In [62]:
# max and min
print(torch.max(e))
print(torch.min(e))

tensor(9)
tensor(0)


In [63]:
# product
torch.prod(e)

tensor(0)

In [65]:
# standard deviation
torch.std(d)

tensor(1.9664)

In [66]:
# vairance
torch.var(d)

tensor(3.8667)

In [67]:
# argmax
torch.argmax(e) # tells the position of the lastest elemnt in the given tensor


tensor(1)

In [68]:
# argmin - tells the index of the lowest number in the given tensor
torch.argmin(e)

tensor(3)

MATRIX OPERATION

In [71]:
f = torch.randint(size = (2,3) , low = 0 , high = 10)
g = torch.randint(size = (3,2) , low = 0 , high = 10 )
print(f)
print(g)

tensor([[4, 0, 8],
        [4, 7, 2]])
tensor([[3, 8],
        [5, 6],
        [2, 9]])


In [72]:
# matrix multiplication
torch.matmul(f,g)

tensor([[ 28, 104],
        [ 51,  92]])

In [73]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

In [74]:
# dot product between 2 vectors
torch.dot(vector1 , vector2)

tensor(11)

In [76]:
# transpose
torch.transpose(f , 0 ,1)

tensor([[4, 4],
        [0, 7],
        [8, 2]])

In [78]:
h = torch.randint( size = (3,3) , low = 0 , high = 10 , dtype = torch.float32)
h

tensor([[4., 1., 1.],
        [2., 4., 7.],
        [2., 5., 6.]])

In [79]:
# determinent
torch.det(h)

tensor(-40.0000)

In [80]:
# inverse
torch.inverse(h)

tensor([[ 0.2750,  0.0250, -0.0750],
        [-0.0500, -0.5500,  0.6500],
        [-0.0500,  0.4500, -0.3500]])

In [81]:
i = torch.randint(size =(2,3) , low = 0 , high = 10)
f = torch.randint(size=(2,3) , low = 0 , high = 10)
print(i)
print(f)

tensor([[1, 4, 5],
        [6, 9, 2]])
tensor([[3, 1, 0],
        [2, 1, 2]])


In [82]:
# comparision
# GREATER THAN
print(i>f)

# less than
print(i<f)

# equal to
print(i==f)

# not equal to
print(i!=f)

tensor([[False,  True,  True],
        [ True,  True, False]])
tensor([[ True, False, False],
        [False, False, False]])
tensor([[False, False, False],
        [False, False,  True]])
tensor([[ True,  True,  True],
        [ True,  True, False]])


SOEACIALISTAION FUNCTION

In [84]:
k = torch.randint(size= (2,3) ,low = 0 , high = 10)
k

tensor([[7, 9, 2],
        [4, 6, 6]])

In [85]:
torch.log(k)

tensor([[1.9459, 2.1972, 0.6931],
        [1.3863, 1.7918, 1.7918]])

In [86]:
torch.exp(k)

tensor([[1.0966e+03, 8.1031e+03, 7.3891e+00],
        [5.4598e+01, 4.0343e+02, 4.0343e+02]])

In [87]:
torch.sqrt(k)

tensor([[2.6458, 3.0000, 1.4142],
        [2.0000, 2.4495, 2.4495]])

In [88]:
# sigmod
torch.sigmoid(k)

tensor([[0.9991, 0.9999, 0.8808],
        [0.9820, 0.9975, 0.9975]])

In [89]:
# softmax
k = torch.randint(size = ( 2,3) , low = 0 , high = 10 , dtype = torch.float32)
torch.softmax(k , dim = 0)

tensor([[9.9966e-01, 4.7426e-02, 5.0000e-01],
        [3.3535e-04, 9.5257e-01, 5.0000e-01]])

In [90]:
# relu
torch.relu(k)

tensor([[8., 4., 9.],
        [0., 7., 9.]])

INPLACE OPERATIONS

In [93]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.4436, 0.3847, 0.4521],
        [0.5569, 0.9952, 0.0015]])
tensor([[0.0813, 0.4907, 0.2130],
        [0.4603, 0.1386, 0.0277]])


In [95]:
m+n
# when we do such additions , it occupises new space in the memory
# not at all ideal in situations where we have very large tensors
# there exist a function with the help of which we can make changes to the orignal tensor only

tensor([[0.5249, 0.8755, 0.6651],
        [1.0172, 1.1338, 0.0292]])

In [97]:
m.add_(n)
m
# with the help of thsi function , the addition is done in the m tensor only

tensor([[0.6062, 1.3662, 0.8781],
        [1.4775, 1.2725, 0.0569]])

In [98]:
m.relu_() # permanenet changes

tensor([[0.6062, 1.3662, 0.8781],
        [1.4775, 1.2725, 0.0569]])

In [ ]:
# u can just mention ur function and type an _ in front of it to make it an INPLACE OPERATION

In [100]:
# copying a tensor
b=m
# but the problem with this function / method is
# ANY CHANGE MADE TO THE ORIGNAL TENSOR WILL BE COPIED INTO THE NEW TENSOR

In [101]:
m[0][0] = 0
m

tensor([[0.0000, 1.3662, 0.8781],
        [1.4775, 1.2725, 0.0569]])

In [102]:
b

tensor([[0.0000, 1.3662, 0.8781],
        [1.4775, 1.2725, 0.0569]])

In [105]:
b = k.clone()
#this function ll ensure that the copy wont undergo the same changes

In [106]:
k

tensor([[8., 4., 9.],
        [0., 7., 9.]])

In [109]:
b

tensor([[8., 4., 9.],
        [0., 7., 9.]])

In [108]:
k[0][0] = 0

In [110]:
torch.cuda.is_available()

True

In [111]:
device = torch.device("cuda")

In [113]:
# creating a new tesnor on GPU
torch.rand((3,2) , device = device)

tensor([[0.3563, 0.0303],
        [0.7088, 0.2009],
        [0.0224, 0.9896]], device='cuda:0')

In [115]:
# we can also move the existing tensor to GPU
a = torch.rand(2,3)
a.to(device)

tensor([[0.6458, 0.3673, 0.1770],
        [0.2966, 0.9925, 0.2103]], device='cuda:0')

In [118]:
import time
size = 10000

# creating random matrix at cpu
matrix_cpu1 = torch.randn(size , size)
matrix_cpu2 = torch.randn(size , size)

# measure time on cpu
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1 , matrix_cpu2)
cpu_time = time.time() - start_time
print(f"TIME on CPU:{cpu_time:.4f} seconds")

# MOVING the matrix to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1 , matrix_gpu2)
torch.cuda.synchronize()
gpu_time = time.time() - start_time
print(f"time on GPU:{gpu_time:4f} seconds")
print(cpu_time / gpu_time)

TIME on CPU:16.5119 seconds
time on GPU:0.567701 seconds
29.085534021723472


RESHAPING TENSOR

In [119]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [122]:
# reshape
a.reshape(2,2,2,2)
# product of the original shape is the same as the new shape

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [123]:
# fatten - repsonsible for changing the daimention to 1
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [124]:
b = torch.rand(2,3,4)
b

tensor([[[0.8828, 0.1579, 0.7480, 0.2873],
         [0.3745, 0.2212, 0.9611, 0.6949],
         [0.9178, 0.5170, 0.9635, 0.0391]],

        [[0.9115, 0.9731, 0.3717, 0.2427],
         [0.5317, 0.3214, 0.8081, 0.4860],
         [0.9501, 0.1150, 0.5921, 0.2218]]])

In [125]:
# permute
b = torch.rand(2,3,4)
print(b)
# the values inside the permute are the index numbers of the values in the orginal b parameters
print(b.permute(2,0,1))


tensor([[[0.7842, 0.3872, 0.1603, 0.7237],
         [0.8044, 0.2652, 0.8645, 0.8437],
         [0.1373, 0.1582, 0.8998, 0.9019]],

        [[0.7039, 0.2528, 0.5547, 0.0540],
         [0.7816, 0.8045, 0.3261, 0.2135],
         [0.0740, 0.1520, 0.8060, 0.6517]]])
tensor([[[0.7842, 0.8044, 0.1373],
         [0.7039, 0.7816, 0.0740]],

        [[0.3872, 0.2652, 0.1582],
         [0.2528, 0.8045, 0.1520]],

        [[0.1603, 0.8645, 0.8998],
         [0.5547, 0.3261, 0.8060]],

        [[0.7237, 0.8437, 0.9019],
         [0.0540, 0.2135, 0.6517]]])


In [126]:
b.permute(2,0,1).reshape

<function Tensor.reshape>

In [128]:
# unsqueese
c = torch.rand(226, 226 , 3)
print(c.unsqueeze(0).shape)
# new daimention added at the given index inside paramenter
print(c.unsqueeze(1).shape)

torch.Size([1, 226, 226, 3])
torch.Size([226, 1, 226, 3])


In [129]:
# Sqyeeze
d = torch.rand(1,20)
d.squeeze(0)

tensor([0.4964, 0.2874, 0.2617, 0.7593, 0.5757, 0.9223, 0.7232, 0.5052, 0.8896,
        0.2267, 0.1560, 0.5830, 0.6520, 0.3877, 0.0564, 0.6084, 0.4443, 0.4796,
        0.5010, 0.0160])

In [130]:
import numpy as np

In [131]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [136]:
b = a.numpy()

In [137]:
b

array([1, 2, 3])

In [138]:
type(b)

numpy.ndarray

In [139]:
c = np.array([1,12,3])
c

array([ 1, 12,  3])

In [140]:
torch.from_numpy(c)

tensor([ 1, 12,  3])